// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.3
// source: gameapp/v1/gameapp.proto

package gameappv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGameAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameAppRequest) Reset() {
	*x = GetGameAppRequest{}
	mi := &file_gameapp_v1_gameapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameAppRequest) ProtoMessage() {}

func (x *GetGameAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameapp_v1_gameapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameAppRequest.ProtoReflect.Descriptor instead.
func (*GetGameAppRequest) Descriptor() ([]byte, []int) {
	return file_gameapp_v1_gameapp_proto_rawDescGZIP(), []int{0}
}

func (x *GetGameAppRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameAppInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId        int64                  `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	AppKey        string                 `protobuf:"bytes,5,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAppInfo) Reset() {
	*x = GameAppInfo{}
	mi := &file_gameapp_v1_gameapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAppInfo) ProtoMessage() {}

func (x *GameAppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gameapp_v1_gameapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAppInfo.ProtoReflect.Descriptor instead.
func (*GameAppInfo) Descriptor() ([]byte, []int) {
	return file_gameapp_v1_gameapp_proto_rawDescGZIP(), []int{1}
}

func (x *GameAppInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameAppInfo) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GameAppInfo) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GameAppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameAppInfo) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type GetGameAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *GameAppInfo           `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameAppResponse) Reset() {
	*x = GetGameAppResponse{}
	mi := &file_gameapp_v1_gameapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameAppResponse) ProtoMessage() {}

func (x *GetGameAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gameapp_v1_gameapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameAppResponse.ProtoReflect.Descriptor instead.
func (*GetGameAppResponse) Descriptor() ([]byte, []int) {
	return file_gameapp_v1_gameapp_proto_rawDescGZIP(), []int{2}
}

func (x *GetGameAppResponse) GetInfo() *GameAppInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CountGameAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountGameAppsRequest) Reset() {
	*x = CountGameAppsRequest{}
	mi := &file_gameapp_v1_gameapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountGameAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountGameAppsRequest) ProtoMessage() {}

func (x *CountGameAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gameapp_v1_gameapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountGameAppsRequest.ProtoReflect.Descriptor instead.
func (*CountGameAppsRequest) Descriptor() ([]byte, []int) {
	return file_gameapp_v1_gameapp_proto_rawDescGZIP(), []int{3}
}

type CountGameAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 总记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountGameAppsResponse) Reset() {
	*x = CountGameAppsResponse{}
	mi := &file_gameapp_v1_gameapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountGameAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountGameAppsResponse) ProtoMessage() {}

func (x *CountGameAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gameapp_v1_gameapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountGameAppsResponse.ProtoReflect.Descriptor instead.
func (*CountGameAppsResponse) Descriptor() ([]byte, []int) {
	return file_gameapp_v1_gameapp_proto_rawDescGZIP(), []int{4}
}

func (x *CountGameAppsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_gameapp_v1_gameapp_proto protoreflect.FileDescriptor

const file_gameapp_v1_gameapp_proto_rawDesc = "" +
	"\n" +
	"\x18gameapp/v1/gameapp.proto\x12\n" +
	"gameapp.v1\"#\n" +
	"\x11GetGameAppRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"z\n" +
	"\vGameAppInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\x03R\x06gameId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x17\n" +
	"\aapp_key\x18\x05 \x01(\tR\x06appKey\"A\n" +
	"\x12GetGameAppResponse\x12+\n" +
	"\x04info\x18\x01 \x01(\v2\x17.gameapp.v1.GameAppInfoR\x04info\"\x16\n" +
	"\x14CountGameAppsRequest\"-\n" +
	"\x15CountGameAppsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total2\xb3\x01\n" +
	"\x0eGameAppService\x12K\n" +
	"\n" +
	"GetGameApp\x12\x1d.gameapp.v1.GetGameAppRequest\x1a\x1e.gameapp.v1.GetGameAppResponse\x12T\n" +
	"\rCountGameApps\x12 .gameapp.v1.CountGameAppsRequest\x1a!.gameapp.v1.CountGameAppsResponseB\x16Z\x14gameapp/v1;gameappv1b\x06proto3"

var (
	file_gameapp_v1_gameapp_proto_rawDescOnce sync.Once
	file_gameapp_v1_gameapp_proto_rawDescData []byte
)

func file_gameapp_v1_gameapp_proto_rawDescGZIP() []byte {
	file_gameapp_v1_gameapp_proto_rawDescOnce.Do(func() {
		file_gameapp_v1_gameapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gameapp_v1_gameapp_proto_rawDesc), len(file_gameapp_v1_gameapp_proto_rawDesc)))
	})
	return file_gameapp_v1_gameapp_proto_rawDescData
}

var file_gameapp_v1_gameapp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gameapp_v1_gameapp_proto_goTypes = []any{
	(*GetGameAppRequest)(nil),     // 0: gameapp.v1.GetGameAppRequest
	(*GameAppInfo)(nil),           // 1: gameapp.v1.GameAppInfo
	(*GetGameAppResponse)(nil),    // 2: gameapp.v1.GetGameAppResponse
	(*CountGameAppsRequest)(nil),  // 3: gameapp.v1.CountGameAppsRequest
	(*CountGameAppsResponse)(nil), // 4: gameapp.v1.CountGameAppsResponse
}
var file_gameapp_v1_gameapp_proto_depIdxs = []int32{
	1, // 0: gameapp.v1.GetGameAppResponse.info:type_name -> gameapp.v1.GameAppInfo
	0, // 1: gameapp.v1.GameAppService.GetGameApp:input_type -> gameapp.v1.GetGameAppRequest
	3, // 2: gameapp.v1.GameAppService.CountGameApps:input_type -> gameapp.v1.CountGameAppsRequest
	2, // 3: gameapp.v1.GameAppService.GetGameApp:output_type -> gameapp.v1.GetGameAppResponse
	4, // 4: gameapp.v1.GameAppService.CountGameApps:output_type -> gameapp.v1.CountGameAppsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gameapp_v1_gameapp_proto_init() }
func file_gameapp_v1_gameapp_proto_init() {
	if File_gameapp_v1_gameapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gameapp_v1_gameapp_proto_rawDesc), len(file_gameapp_v1_gameapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gameapp_v1_gameapp_proto_goTypes,
		DependencyIndexes: file_gameapp_v1_gameapp_proto_depIdxs,
		MessageInfos:      file_gameapp_v1_gameapp_proto_msgTypes,
	}.Build()
	File_gameapp_v1_gameapp_proto = out.File
	file_gameapp_v1_gameapp_proto_goTypes = nil
	file_gameapp_v1_gameapp_proto_depIdxs = nil
}
