// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.3
// source: gameapp/v1/gameapp.proto

package gameappv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameAppService_GetGameApp_FullMethodName    = "/gameapp.v1.GameAppService/GetGameApp"
	GameAppService_CountGameApps_FullMethodName = "/gameapp.v1.GameAppService/CountGameApps"
)

// GameAppServiceClient is the client API for GameAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameAppServiceClient interface {
	GetGameApp(ctx context.Context, in *GetGameAppRequest, opts ...grpc.CallOption) (*GetGameAppResponse, error)
	// 统计游戏APP数量
	CountGameApps(ctx context.Context, in *CountGameAppsRequest, opts ...grpc.CallOption) (*CountGameAppsResponse, error)
}

type gameAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameAppServiceClient(cc grpc.ClientConnInterface) GameAppServiceClient {
	return &gameAppServiceClient{cc}
}

func (c *gameAppServiceClient) GetGameApp(ctx context.Context, in *GetGameAppRequest, opts ...grpc.CallOption) (*GetGameAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameAppResponse)
	err := c.cc.Invoke(ctx, GameAppService_GetGameApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameAppServiceClient) CountGameApps(ctx context.Context, in *CountGameAppsRequest, opts ...grpc.CallOption) (*CountGameAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountGameAppsResponse)
	err := c.cc.Invoke(ctx, GameAppService_CountGameApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameAppServiceServer is the server API for GameAppService service.
// All implementations must embed UnimplementedGameAppServiceServer
// for forward compatibility.
type GameAppServiceServer interface {
	GetGameApp(context.Context, *GetGameAppRequest) (*GetGameAppResponse, error)
	// 统计游戏APP数量
	CountGameApps(context.Context, *CountGameAppsRequest) (*CountGameAppsResponse, error)
	mustEmbedUnimplementedGameAppServiceServer()
}

// UnimplementedGameAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameAppServiceServer struct{}

func (UnimplementedGameAppServiceServer) GetGameApp(context.Context, *GetGameAppRequest) (*GetGameAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameApp not implemented")
}
func (UnimplementedGameAppServiceServer) CountGameApps(context.Context, *CountGameAppsRequest) (*CountGameAppsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountGameApps not implemented")
}
func (UnimplementedGameAppServiceServer) mustEmbedUnimplementedGameAppServiceServer() {}
func (UnimplementedGameAppServiceServer) testEmbeddedByValue()                        {}

// UnsafeGameAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameAppServiceServer will
// result in compilation errors.
type UnsafeGameAppServiceServer interface {
	mustEmbedUnimplementedGameAppServiceServer()
}

func RegisterGameAppServiceServer(s grpc.ServiceRegistrar, srv GameAppServiceServer) {
	// If the following call panics, it indicates UnimplementedGameAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameAppService_ServiceDesc, srv)
}

func _GameAppService_GetGameApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameAppServiceServer).GetGameApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameAppService_GetGameApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameAppServiceServer).GetGameApp(ctx, req.(*GetGameAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameAppService_CountGameApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountGameAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameAppServiceServer).CountGameApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameAppService_CountGameApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameAppServiceServer).CountGameApps(ctx, req.(*CountGameAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameAppService_ServiceDesc is the grpc.ServiceDesc for GameAppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameAppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gameapp.v1.GameAppService",
	HandlerType: (*GameAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameApp",
			Handler:    _GameAppService_GetGameApp_Handler,
		},
		{
			MethodName: "CountGameApps",
			Handler:    _GameAppService_CountGameApps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gameapp/v1/gameapp.proto",
}
