server:
  http:
    addr: 0.0.0.0:8080
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root123456@tcp(127.0.0.1:3306)/game_sdk_cn?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 1
# 客户端配置
clients:
  # 用户服务配置
  user:
    endpoint: 127.0.0.1:9100
  game_app:
    endpoint: 127.0.0.1:9200
auth:
  jwt:
    password: change-me-user-service-jwt-secret
    expire_seconds: 86400
