// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway-service/internal/biz"
	"gateway-service/internal/conf"
	"gateway-service/internal/data"
	"gateway-service/internal/server"
	"gateway-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRedis *conf.RedisConfig, confAuth *conf.JWTAuthConfig, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, confRedis)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	userRepo := data.NewUserRepo(logger)
	userUseCase := biz.NewUserUsecase(userRepo)
	gameAppRepo := data.NewGameAppRepo(logger)
	gameAppUseCase := biz.NewGameAppUseCase(gameAppRepo)
	gatewayService := service.NewGatewayService(userUseCase, gameAppUseCase)
	httpServer := server.NewHTTPServer(confServer, confAuth, dataData, greeterService, gatewayService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
