// Copyright 2024 The Terway Authors. All rights reserved.
//版权说明

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.3
// source: gateway/v1/gateway.proto

// 3. package（重要！Kratos 生成路径靠它）

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // 用户邮箱
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 用户密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // 用户姓名
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // 用户 token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SearchUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`      // 用户 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`   // 用户姓名
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // 用户邮箱
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUser) Reset() {
	*x = SearchUser{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUser) ProtoMessage() {}

func (x *SearchUser) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUser.ProtoReflect.Descriptor instead.
func (*SearchUser) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *SearchUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
	Search        *SearchUser            `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`                      // 搜索条件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetSearch() *SearchUser {
	if x != nil {
		return x.Search
	}
	return nil
}

type ListUsersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 用户总数
	Users         []*SearchUser          `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`  // 用户列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersReply) Reset() {
	*x = ListUsersReply{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersReply) ProtoMessage() {}

func (x *ListUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersReply.ProtoReflect.Descriptor instead.
func (*ListUsersReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUsersReply) GetUsers() []*SearchUser {
	if x != nil {
		return x.Users
	}
	return nil
}

// 查询用户请求
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 查询用户响应
type GetUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`      // 用户 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`   // 用户姓名
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // 用户邮箱
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReply) Reset() {
	*x = GetUserReply{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReply) ProtoMessage() {}

func (x *GetUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReply.ProtoReflect.Descriptor instead.
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetGameAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 游戏应用 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameAppRequest) Reset() {
	*x = GetGameAppRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameAppRequest) ProtoMessage() {}

func (x *GetGameAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameAppRequest.ProtoReflect.Descriptor instead.
func (*GetGameAppRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *GetGameAppRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameAppInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                      // 游戏应用 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                   // 游戏应用名称
	GameId        string                 `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // 游戏 ID
	AppKey        string                 `protobuf:"bytes,4,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"` // 游戏应用 Key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAppInfo) Reset() {
	*x = GameAppInfo{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAppInfo) ProtoMessage() {}

func (x *GameAppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAppInfo.ProtoReflect.Descriptor instead.
func (*GameAppInfo) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *GameAppInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameAppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameAppInfo) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameAppInfo) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type GetGameAppReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameApp       *GameAppInfo           `protobuf:"bytes,1,opt,name=game_app,json=gameApp,proto3" json:"game_app,omitempty"` // 游戏应用信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameAppReply) Reset() {
	*x = GetGameAppReply{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameAppReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameAppReply) ProtoMessage() {}

func (x *GetGameAppReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameAppReply.ProtoReflect.Descriptor instead.
func (*GetGameAppReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *GetGameAppReply) GetGameApp() *GameAppInfo {
	if x != nil {
		return x.GameApp
	}
	return nil
}

type GetUserGameAppStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGameAppStatsRequest) Reset() {
	*x = GetUserGameAppStatsRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGameAppStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGameAppStatsRequest) ProtoMessage() {}

func (x *GetUserGameAppStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGameAppStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserGameAppStatsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

type GetUserGameAppStatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers    int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`            // 用户总数
	TotalGameApps int64                  `protobuf:"varint,2,opt,name=total_game_apps,json=totalGameApps,proto3" json:"total_game_apps,omitempty"` // 游戏应用总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserGameAppStatsReply) Reset() {
	*x = GetUserGameAppStatsReply{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserGameAppStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserGameAppStatsReply) ProtoMessage() {}

func (x *GetUserGameAppStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserGameAppStatsReply.ProtoReflect.Descriptor instead.
func (*GetUserGameAppStatsReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserGameAppStatsReply) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetUserGameAppStatsReply) GetTotalGameApps() int64 {
	if x != nil {
		return x.TotalGameApps
	}
	return 0
}

type GameAppsSearch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// optional 表示字段是可选的，可以不提供
	TypeOs        *int32 `protobuf:"varint,2,opt,name=type_os,json=typeOs,proto3,oneof" json:"type_os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAppsSearch) Reset() {
	*x = GameAppsSearch{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAppsSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAppsSearch) ProtoMessage() {}

func (x *GameAppsSearch) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAppsSearch.ProtoReflect.Descriptor instead.
func (*GameAppsSearch) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *GameAppsSearch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameAppsSearch) GetTypeOs() int32 {
	if x != nil && x.TypeOs != nil {
		return *x.TypeOs
	}
	return 0
}

type ListGameAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        *GameAppsSearch        `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGameAppsRequest) Reset() {
	*x = ListGameAppsRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGameAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGameAppsRequest) ProtoMessage() {}

func (x *ListGameAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGameAppsRequest.ProtoReflect.Descriptor instead.
func (*ListGameAppsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *ListGameAppsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListGameAppsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGameAppsRequest) GetSearch() *GameAppsSearch {
	if x != nil {
		return x.Search
	}
	return nil
}

type GameAppInfoV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId        int64                  `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	AppKey        string                 `protobuf:"bytes,5,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameAppInfoV2) Reset() {
	*x = GameAppInfoV2{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameAppInfoV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAppInfoV2) ProtoMessage() {}

func (x *GameAppInfoV2) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAppInfoV2.ProtoReflect.Descriptor instead.
func (*GameAppInfoV2) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *GameAppInfoV2) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameAppInfoV2) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GameAppInfoV2) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GameAppInfoV2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameAppInfoV2) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type ListGameAppsReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 游戏APP列表
	// repeated 表示一个字段可以有多个值，类似于数组或列表
	Infos         []*GameAppInfoV2 `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	Total         uint64           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGameAppsReply) Reset() {
	*x = ListGameAppsReply{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGameAppsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGameAppsReply) ProtoMessage() {}

func (x *ListGameAppsReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGameAppsReply.ProtoReflect.Descriptor instead.
func (*ListGameAppsReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *ListGameAppsReply) GetInfos() []*GameAppInfoV2 {
	if x != nil {
		return x.Infos
	}
	return nil
}

func (x *ListGameAppsReply) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\x1a\x1cgoogle/api/annotations.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"6\n" +
	"\n" +
	"LoginReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"F\n" +
	"\n" +
	"SearchUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"s\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12.\n" +
	"\x06search\x18\x03 \x01(\v2\x16.gateway.v1.SearchUserR\x06search\"T\n" +
	"\x0eListUsersReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12,\n" +
	"\x05users\x18\x02 \x03(\v2\x16.gateway.v1.SearchUserR\x05users\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"H\n" +
	"\fGetUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"#\n" +
	"\x11GetGameAppRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"c\n" +
	"\vGameAppInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\tR\x06gameId\x12\x17\n" +
	"\aapp_key\x18\x04 \x01(\tR\x06appKey\"E\n" +
	"\x0fGetGameAppReply\x122\n" +
	"\bgame_app\x18\x01 \x01(\v2\x17.gateway.v1.GameAppInfoR\agameApp\"\x1c\n" +
	"\x1aGetUserGameAppStatsRequest\"c\n" +
	"\x18GetUserGameAppStatsReply\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12&\n" +
	"\x0ftotal_game_apps\x18\x02 \x01(\x03R\rtotalGameApps\"N\n" +
	"\x0eGameAppsSearch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\atype_os\x18\x02 \x01(\x05H\x00R\x06typeOs\x88\x01\x01B\n" +
	"\n" +
	"\b_type_os\"z\n" +
	"\x13ListGameAppsRequest\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x122\n" +
	"\x06search\x18\x04 \x01(\v2\x1a.gateway.v1.GameAppsSearchR\x06search\"|\n" +
	"\rGameAppInfoV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\x03R\x06gameId\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x17\n" +
	"\aapp_key\x18\x05 \x01(\tR\x06appKey\"Z\n" +
	"\x11ListGameAppsReply\x12/\n" +
	"\x05infos\x18\x01 \x03(\v2\x19.gateway.v1.GameAppInfoV2R\x05infos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total2\x84\x05\n" +
	"\x0eGatewayService\x12O\n" +
	"\x05Login\x12\x18.gateway.v1.LoginRequest\x1a\x16.gateway.v1.LoginReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login\x12^\n" +
	"\x0eGetGatewayInfo\x12\x1a.gateway.v1.GetUserRequest\x1a\x18.gateway.v1.GetUserReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/users/{id}\x12c\n" +
	"\x11ListUsersWithPage\x12\x1c.gateway.v1.ListUsersRequest\x1a\x1a.gateway.v1.ListUsersReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12c\n" +
	"\n" +
	"GetGameApp\x12\x1d.gateway.v1.GetGameAppRequest\x1a\x1b.gateway.v1.GetGameAppReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/game_app/{id}\x12p\n" +
	"\x14ListGameAppsWithPage\x12\x1f.gateway.v1.ListGameAppsRequest\x1a\x1d.gateway.v1.ListGameAppsReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/game_apps\x12\x84\x01\n" +
	"\x13GetUserGameAppStats\x12&.gateway.v1.GetUserGameAppStatsRequest\x1a$.gateway.v1.GetUserGameAppStatsReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/user_game_app_statsB#Z!gateway-service/api/gateway/v1;v1b\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(*LoginRequest)(nil),               // 0: gateway.v1.LoginRequest
	(*LoginReply)(nil),                 // 1: gateway.v1.LoginReply
	(*SearchUser)(nil),                 // 2: gateway.v1.SearchUser
	(*ListUsersRequest)(nil),           // 3: gateway.v1.ListUsersRequest
	(*ListUsersReply)(nil),             // 4: gateway.v1.ListUsersReply
	(*GetUserRequest)(nil),             // 5: gateway.v1.GetUserRequest
	(*GetUserReply)(nil),               // 6: gateway.v1.GetUserReply
	(*GetGameAppRequest)(nil),          // 7: gateway.v1.GetGameAppRequest
	(*GameAppInfo)(nil),                // 8: gateway.v1.GameAppInfo
	(*GetGameAppReply)(nil),            // 9: gateway.v1.GetGameAppReply
	(*GetUserGameAppStatsRequest)(nil), // 10: gateway.v1.GetUserGameAppStatsRequest
	(*GetUserGameAppStatsReply)(nil),   // 11: gateway.v1.GetUserGameAppStatsReply
	(*GameAppsSearch)(nil),             // 12: gateway.v1.GameAppsSearch
	(*ListGameAppsRequest)(nil),        // 13: gateway.v1.ListGameAppsRequest
	(*GameAppInfoV2)(nil),              // 14: gateway.v1.GameAppInfoV2
	(*ListGameAppsReply)(nil),          // 15: gateway.v1.ListGameAppsReply
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	2,  // 0: gateway.v1.ListUsersRequest.search:type_name -> gateway.v1.SearchUser
	2,  // 1: gateway.v1.ListUsersReply.users:type_name -> gateway.v1.SearchUser
	8,  // 2: gateway.v1.GetGameAppReply.game_app:type_name -> gateway.v1.GameAppInfo
	12, // 3: gateway.v1.ListGameAppsRequest.search:type_name -> gateway.v1.GameAppsSearch
	14, // 4: gateway.v1.ListGameAppsReply.infos:type_name -> gateway.v1.GameAppInfoV2
	0,  // 5: gateway.v1.GatewayService.Login:input_type -> gateway.v1.LoginRequest
	5,  // 6: gateway.v1.GatewayService.GetGatewayInfo:input_type -> gateway.v1.GetUserRequest
	3,  // 7: gateway.v1.GatewayService.ListUsersWithPage:input_type -> gateway.v1.ListUsersRequest
	7,  // 8: gateway.v1.GatewayService.GetGameApp:input_type -> gateway.v1.GetGameAppRequest
	13, // 9: gateway.v1.GatewayService.ListGameAppsWithPage:input_type -> gateway.v1.ListGameAppsRequest
	10, // 10: gateway.v1.GatewayService.GetUserGameAppStats:input_type -> gateway.v1.GetUserGameAppStatsRequest
	1,  // 11: gateway.v1.GatewayService.Login:output_type -> gateway.v1.LoginReply
	6,  // 12: gateway.v1.GatewayService.GetGatewayInfo:output_type -> gateway.v1.GetUserReply
	4,  // 13: gateway.v1.GatewayService.ListUsersWithPage:output_type -> gateway.v1.ListUsersReply
	9,  // 14: gateway.v1.GatewayService.GetGameApp:output_type -> gateway.v1.GetGameAppReply
	15, // 15: gateway.v1.GatewayService.ListGameAppsWithPage:output_type -> gateway.v1.ListGameAppsReply
	11, // 16: gateway.v1.GatewayService.GetUserGameAppStats:output_type -> gateway.v1.GetUserGameAppStatsReply
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	file_gateway_v1_gateway_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
