server:
  http:
    addr: 0.0.0.0:8003
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9300
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
rabbitmq:
  url: amqp://admin:admin123@127.0.0.1:5672/
  queue: access_log
  consumer_tag: accesslog-service
  auto_ack: false
  prefetch_count: 1
